---
#
# got this idea from https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# with some small changes to support mutilple CNI plugins and different versions of k8s 
#
- hosts: all
  become: true
  tasks:
  - name: Show parameters used to provision k8s cluster
    debug: 
      msg: 
        - 'Using CNI {{ k8s_cni }}'
        - 'Using k8s version {{ k8s_version  }}'

  - name: Check cni is valid
    assert: 
      that: k8s_cni in ( 'weavenet','calico','flannel' )
      fail_msg: "That is not a valid value for the CNI only supported values are 'weavnet','calico','flannel'"

  - name: Include node tasks
    include: common/node-tasks.yaml

  - name: Include CNI
    include: cni/{{k8s_cni | lower}}-cni.yml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: "copy content='{{ join_command.stdout_lines[0] }}' dest='./join-command'"
    vars:
     ansible_become: no

  - name: get kubeconfig conf file
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: kubeconfig.conf
      remote_src: yes
      force: yes 
      
  handlers:
    - include: handler/handlers.yml